### PR TITLE
kriteen - feature on the course history page (okay to type cs156 for course number) 

### LINKED ISSUE #12: FEATURE: On the course history page, it is easier for users to search for classes
### Have you updated the title?

- [x] I have updated the issue's title.

### As a...

user

### I can...

search for 'CS156' instead of just '156'

### So that...

it's easier to search for courses. 

### Discussion

On the course history page, you are currently unable to search for 'CS156' and are not given any error message. We would like to change it so that you are able to search for 'CS156' and results for '156' would show up. This is so that users that are used to putting 'CS' or any department name in front of the course number are not set back in the search. 

**Although the example I am using in this issue is for 'CS', we expect this to work for all departments and any non-digit characters that the user inputs before the course number. 

Current output when 'CS156' is searched: 
image

Expected output when 'CS156' is searched: 
image

### Acceptance Criteria

- [ ] on the course history page, when a user searches for 'CS156', the result is the same as if you searched '156'. 

### Implementation Todos

Backend:
- [ ] Right before the API is called, add a check to make sure the input matches the expected format (digits only) and if it doesn't, parse through the input and truncate it to be in the expected format. 

Testing:
- [ ] Back end tests pass and there is adequate coverage

### PR DESCRIPTION
**Pull request by kriteenshrestha**
In this PR, I edited the CourseOverTimeSearch form so that, on the Course History Search Page, if a user is used to typing CS156 as a course number, it will still accept that input and interpret the input's course number as 156. In other words, on the course history page, if a user searches for "CS156", you get equivalent results if you typed '156'. I added a check so that we remove all non-digits from courseNumber, and suffix parsing stays the same. I have also added tests to CourseOverTimeSearchFormTest.js to make sure this works.

I have also added more checks so if letters that don't match the subject area (i.e. CMPSC) are before the digits, it will not go into the search, and also if there are no digits that will also not go into the search; so inputs like the following will not lead to any search results:

"LKFJLKSDJLSF156"
image

"CMPSC"
image

Because many users may be used to other names for "CMPSC" (like CS and COMS), I also allowed those subject areas to be inputted in the courseNumber field. That is, if the following were inputted in courseNumber, it would still be allowed (case insensitive):

"cmPSC156"
image

"CS156"
image

"COMS156"
image

"cs130a"
image

(etc, with also case insensitive cases)

Here, you can see in the image below that when I type "130A" or "CMPSC130A", I get the same search results.
image
image

dokku deployment: https://proj-kriteenshrestha-dev.dokku-02.cs.ucsb.edu/courseovertime/search

Closes #12 .

### CODE REVIEW

**Review by jchanDev — COMMENTED** [review]
i feel like LMAO 16 should not pull up cs 16.

**Review by pconrad — DISMISSED** [review]
Please remove package-lock.json from the PR.

See: https://ucsb-cs156.github.io/topics/pull_requests/package_lock_json.html

**Comment by pconrad** [comment]
> i feel like LMAO 16 should not pull up cs 16.

That's a legitimate concern.  On the other hand, what would you do instead?  Which of these would you accept/reject and on what basis:

* `CMPSC 16`
* `CMPSC16`
* `CS16`
* `COMS 16`  Note that this, weirdly, is the abbreviation used by the UCSB Library and the Office of Research for Computer Science, even though no one else uses it.

I sort of feel like the current solution of ignoring all letters before the first digit is ... maybe the least bad approach.

**Comment by pconrad** [comment]
I added FIXME-Team Cr needed because the current team CR is not an approving one.

**Comment by kriteenshrestha** [comment]
> > i feel like LMAO 16 should not pull up cs 16.
> 
> That's a legitimate concern. On the other hand, what would you do instead? Which of these would you accept/reject and on what basis:
> 
> * `CMPSC 16`
> * `CMPSC16`
> * `CS16`
> * `COMS 16`  Note that this, weirdly, is the abbreviation used by the UCSB Library and the Office of Research for Computer Science, even though no one else uses it.
> 
> I sort of feel like the current solution of ignoring all letters before the first digit is ... maybe the least bad approach.

I am currently working on this! I am making it so that it accepts the first 3, I will add the second one, and update this PR soon!

**Review by kai-maeda — DISMISSED** [review]
LGTM

**Review by whuang602 — DISMISSED** [review]
Could you remove the package-lock.json?

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
