### PR TITLE
Kriteen - h2enable feature

### LINKED ISSUE #16: FEATURE: H2 Console Enable
Allowing users to turn on/off the H2 console via a variable called H2_CONSOLE_ENABLED.

 When the config variable on dokku H2_CONSOLE_ENABLED is set to true, the H2 Console shows up
 When the config variable on dokku H2_CONSOLE_ENABLED is set to false, the H2 Console does NOT show up.

### PR DESCRIPTION
**Pull request by kriteenshrestha**
In this PR, I changed the resource file, similar to #8, so that we added the environment variable that enables the H2 console viewing option.
image

dokku deployment: https://proj-kriteenshrestha-dev.dokku-02.cs.ucsb.edu

Closes #16

### CODE REVIEW

**Review by evanja57 — DISMISSED** [review]
When I run this locally, I cannot get the H2 console to turn off even with the environment variable. If in AppNavbar.js the line (45): 
              {systemInfo?.springH2ConsoleEnabled && (
is changed to
               {systemInfo?.showH2Console && (
this feature will work as intended.

**Comment by kriteenshrestha** [comment]
Fixed it!

**Review by jchanDev — COMMENTED** [review]
src/main/resources/application-development.properties has a comment on line 7

**Review by whuang602 — DISMISSED** [review]
Could you also remove package.json and address the merge conflict?

**Review by jchanDev — DISMISSED** [review]
LGTM, comment has been removed

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
