### PR TITLE
BUG: Add course dialog allows adding course to the wrong schedule

### LINKED ISSUE #24: When you click the add button for a course in a given quarter, say F24, in the modal that pops up, all of the personal schedules for that quarter are shown, and ONLY the personal schedules for that quarter are shown.   (NOTE: This could be factored out into it's own issue an PR).

### PR DESCRIPTION
**Pull request by WhrainySu**
In this PR, I achieved two goals:
1. When the user clicks the add button for a course in a given quarter, say F24, in the modal that pops up, all of the personal schedules for that quarter are shown, and ONLY the personal schedules for that quarter are shown.

2. When the user clicks the add button for a course in a given quarter, say F24, if there are no personal schedules for that quarter that already exist, the modal says: "There are no personal schedules for F24" (or whatever the quarter is), and there is a button [Create Personal Schedule] that when the user clicks it, navigates to the create page.

The following is the steps to operate:
1. Create two new schedules, S23 and S24
image

2. Seach courses in quarter S24 ( schedule already exist), and try to add a course
image
image

    We can see that only schedule for S24 is shown, and CS 5A is successfully added.

3. Seach courses in quarter F24 ( schedule not exist), and try to add a course
image

    We can see that there is no schedule for F24, and we can create a new schedule for it by clicking the link.

4. Create a schedule for F24, and try to add a course
image
image
image

    We can see that there is a new schedule for F24, and CS 5A is successfully added.

Dokku Link: https://project-whrainysu-dev.dokku-02.cs.ucsb.edu
Close: #24 #25

### CODE REVIEW

**Review by pconrad — DISMISSED** [review]
[@Yusheng Su](https://ucsb-cs156-s24.slack.com/team/U06RS3TPXHA)
 For your PR https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/35/files  ....
There are 21 changed files.  Most of the files are not really changed; they just have whitespace changes.
But this makes it very hard to review your code.
I think the files with legitimate changes are these seven files:
* frontend/src/main/components/PersonalSchedules/AddToScheduleModal.js
* frontend/src/main/components/PersonalSchedules/PersonalScheduleSelector.js
* frontend/src/main/components/Sections/SectionsTable.js
* frontend/src/main/utils/PersonalScheduleUtils.js
* frontend/src/tests/components/PersonalSchedules/AddToScheduleModal.test.js
* frontend/src/tests/components/PersonalSchedules/PersonalScheduleSelector.test.js
* frontend/src/tests/utils/PersonalScheduleUtils.test.js

Please make a new PR where you have:

* Only the changes to these seven files and no  others (unless I have overlooked something critical to your PR)
* All commented out code removed.
* A dokku deployment
* A peer CR
* All tests passing

**Review by kmflippo — APPROVED** [review]
LGTM nice job!

**Review by pconrad — DISMISSED** [review]
Not working on the dokku linked in the PR description

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
