### PR TITLE
Kai Better UI and UX in Main Course Search Page

### LINKED ISSUE #10: FEATURE: Better UI and UX in Main Course Search Page
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

user

### I can...

more easily find and add correct lecture and section to my schedule

### So that...

I can avoid mistakes and confusion when choosing sections

### Discussion

Currently the Main Search Page looks like this:
Screenshot 2024-05-15 at 5 07 32 PM

The inconsistency between the `Add` button and the lack thereof makes it a confusing experience for new users when they want to add a new course to their schedule.

And when they finally figure out they need to expand the lecture to select a specific section, they are met with inconsistent UI.

Screenshot 2024-05-15 at 5 17 20 PM

### Acceptance Criteria

- [ ] There is an "Action" column that displays an "Add" button for sections and an "Expand" button for lectures WITh sections
- [ ] The "Add" button actually allows you to add a course
- [ ] The "Expand" button actually allows you to expand the lecture row and show the sections
- [ ] Remove the + button for lectures

### Implementation Todos

Frontend:
- [ ] An "action" column separate from other columns 
- [ ] There's an "Add" button in the action column for sections
- [ ] There's an "Expand" button in the action column for lectures

Backend:
- [ ] Ensure both buttons still work as intended, the backend code should already exist

Testing:
- [ ] Front end tests pass and there is adequate coverage
- [ ] If additional backend code is added, the Back end tests pass and there is adequate coverage

### PR DESCRIPTION
**Pull request by kai-maeda**
FEATURE: Main course search page previously had the dropdown for course sections integrated into the course Id column and has the add button integrated into the enroll code column. To make the UI less confusing, a column called action was added where the dropdown and add button were included. The dropdown button should be in the action column when it is in a row that is a course with sections. The add button should be in the action column when the row is a section or a lecture with no sections.
dokku: https://proj-courses-kai-maeda-dev.dokku-02.cs.ucsb.edu/
Screenshot 2024-05-27 at 7 59 43 PM
Screenshot 2024-05-27 at 8 00 48 PM

Closes #10

### CODE REVIEW

**Review by WhrainySu — COMMENTED** [review]
LGTM, but i think we still need to wait for dokku working.

**Review by jchanDev — DISMISSED** [review]
frontend/src/main/components/Sections/SectionsTable.js line 60 has unneeded comment.

**Review by pconrad — DISMISSED** [review]
Please remove the package-lock.json from the PR.

See: https://ucsb-cs156.github.io/topics/pull_requests/package_lock_json.html

**Review by kmflippo — DISMISSED** [review]
LGTM

**Comment by pconrad** [comment]
Holding for delete on individual courses on the personal scheduled detail page.

**Pull request closed without merging**
